[package]
name = "wiki"
version = "0.1.0"
description = "Generates static HTML files based on markdown files."
authors = ["Rust Leipzig"]

[dependencies]
glob = "0.2"
markdown = "0.2"
clap = "2.20.*"
log = "0.3.6"
mowl = "1.0.1"
